services:
  library-db:
    container_name: library-db
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=library-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /home/containers/library-db/mount:/var/lib/postgresql/data
    networks:
      - library_network

  library-profile:
    container_name: library-profile
    image: library-profile:v1
    entrypoint: ["/bin/sh", "-c", "java -jar library-system.jar"]
    ports:
      - "8080:8080"
    environment:
      - spring_profiles_active=prod
    depends_on:
      - library-db
    networks:
      - library_network

  library-profile-app:
    container_name: library-profile-app
    image: library-profile:v1
    entrypoint: ["/bin/sh", "-c", "serve -s build"]
    ports:
      - "3001:3000"
    depends_on:
      - library-db
      - library-profile
    networks:
      - library_network

networks:
  library_network:
    driver: bridge


