CREATE VIEW VW_RELATORIO_LIVROS AS
SELECT L.ID, L.TITULO, L.ANO_PUBLICACAO, L.EDICAO, L.EDITORA, A.NOME, ASS.DESCRICAO
FROM LIVRO L
         INNER JOIN LIVRO_AUTOR LA ON LA.LIVRO_ID = L.ID
         INNER JOIN AUTOR A ON A.ID = LA.AUTOR_ID
         INNER JOIN LIVRO_ASSUNTO LAS ON LAS.LIVRO_ID = L.ID
         INNER JOIN ASSUNTO ASS ON ASS.ID = LAS.ASSUNTO_ID
GROUP BY A.NOME, L.TITULO, L.ANO_PUBLICACAO, L.EDICAO, L.EDITORA, ASS.DESCRICAO, L.ID
ORDER BY A.NOME ASC